apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          containerConcurrency: 1
          container:
            image: gcr.io/zhiminx-gke-dev/helloworld-go
            env:
            - name: TARGET
              value: "Go Sample v1"
